### ISSUE TITLE
Collapsable Links in Top-Right Mode

### ISSUE THREAD

**Issue by djsegal** [josevalim/rails-footnotes#130]
I'd like a way to close a section when I no longer care about it.  For example, if I click Partials, I see all the partials.  I'd like it, if I clicked Partials again, it collapsed the Partials section that's already open.  

If you need any more info, please let me know.  Thanks!

**Comment by Intrepidd** [comment]
Alright I allowed to collapses notes in both view modes, I just released version 4.1.7 with this fix.

Side note : 
Working on this got me thinking about the way the javascript is injected into the page, I'm wondering if it would be a better idea to add the javascript in sprockets and let the user require it. The downside being it always present even in production, maybe just a helper such as ``footnotes_javascript_tag`` that will only inject the js when necessary.
