### ISSUE TITLE
WIP: Rails 5 Deprecation Warnings

### ISSUE THREAD

**Issue by jasnow** [josevalim/rails-footnotes#132]
When I upgraded our local ruby users group web site, I am going these warnings:
```
 * (twice) DEPRECATION WARNING: prepend_before_filter is deprecated and will be 
removed in Rails 5.1. Use prepend_before_action instead. (called from block in
 <module:RailsFootnotesExtension> at .../rvm/gems/ruby-2.2.3@2.2.3/bundler/
gems/rails-footnotes-0ab80d07b071/lib/rails-footnotes/extension.rb:9)

 * (twice) DEPRECATION WARNING: after_filter is deprecated and will be removed in 
Rails 5.1. Use after_action instead. (called from block in <module:RailsFootnotesExtension> 
at .../.rvm/gems/ruby-2.2.3@2.2.3/bundler/gems/rails-footnotes-0ab80d07b071/
lib/rails-footnotes/extension.rb:10)
```
This could be the start on getting ready for Rails 5.

**Comment by Intrepidd** [comment]
Thanks.

This ones look easy to fix. Do you want to submit a pull request?

Otherwise I'll handle it soon.

**Comment by Intrepidd** [comment]
Ok I removed those particular warnings.

Testing against rails 5 is a pain at the moment because they are pointing on gems that are unreleased and changing very soon, IMO this is unproductive to worry about rails 5 until they release an alpha version as usual
