### ISSUE TITLE
Sublime support should be removed from the documentation, subl-hanlder discontinued

### ISSUE THREAD

**Issue by AntonTrapp** [josevalim/rails-footnotes#139]
It makes no use installing the plugin without editor support. Only wastes the time of sublime users. Probably a good plugin, but I won't change my editor to use it ;)

**Comment by joshuapaling** [comment]
Where's it say that subl-handler has been discontinued?

**Comment by AntonTrapp** [comment]
Latest changes: 2 years ago. Try to download the lates release. 404 - has been so for months. Sublime Text 3 not supported (introduced 2 years ago, I know nobody who is still on version 2). No issues fixed since 2013. ... - it's dead since the beginning of 2014. :(

So to use it
a) I would have to download it, rewrite it to support Sublime Text 3 and new OS X versions - don't have the time right now :(
b) downgrade OS X and my editor to at least 2 years old stuff, download and try to compile it - not really an option for me ;)
c) decide to not use it and that I can't use the rails-footnotes plugin - which is the way I have to go (and probably all OS X users must go)

**Comment by joshuapaling** [comment]
Hmmm... You're right that the download link is dead. But I'm using footnotes with sublhandler (installed from way back), and it works fine with ST3 and latest OSX. So if we could just find a link to download it, we'd be sweet.

**Comment by joshuapaling** [comment]
Correction: It turns out I don't use SublHander, I use https://github.com/dhoulb/subl which is a working equivalent. So, we should just update the docs to reflect that.

**Comment by joshuapaling** [comment]
@AntonTrapp I've submitted a PR for this: https://github.com/josevalim/rails-footnotes/pull/142 Can you test out the new instructions and see if they work for you? You can view the updated readme at https://github.com/joshuapaling/rails-footnotes/tree/fix-sublime-doco

**Comment by AntonTrapp** [comment]
@joshuapaling Thank you very much for your effort. Made a clean install according to the documentation. Working perfect on my Yosemite installation.
As I am working on an AngularJS application the plugin is not so useful for this project. But I clear that in two own issues. For old school server side page creation it saves a ton of time! TNX!
